// Mocks generated by Mockito 5.2.0 from annotations
// in counter_test/test/domain/usecases/counter_usecase.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:counter_test/application/error/failure.dart' as _i5;
import 'package:counter_test/domain/repos/counter_repo.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CounterRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCounterRepo extends _i1.Mock implements _i3.CounterRepo {
  MockCounterRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> readCounter() =>
      (super.noSuchMethod(Invocation.method(#readCounter, []),
              returnValue: Future<_i2.Either<_i5.Failure, int>>.value(
                  _FakeEither_0<_i5.Failure, int>()))
          as _i4.Future<_i2.Either<_i5.Failure, int>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> increment(int? oldCounter) =>
      (super.noSuchMethod(Invocation.method(#increment, [oldCounter]),
              returnValue: Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>()))
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> decrement(int? oldCounter) =>
      (super.noSuchMethod(Invocation.method(#decrement, [oldCounter]),
              returnValue: Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>()))
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
